/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandShortSvg: typeof import('./src/components/app-svg/BrandShortSvg.vue')['default']
    BrandSvg: typeof import('./src/components/app-svg/BrandSvg.vue')['default']
    BrendSvg: typeof import('./src/components/app-svg/BrendSvg.vue')['default']
    Card: typeof import('./src/components/cards/Card.vue')['default']
    DrandShortSvg: typeof import('./src/components/app-svg/DrandShortSvg.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Leftbar: typeof import('./src/components/navbar/Leftbar.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
